### ISSUE TITLE
New search expressions for Starred messages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wangvisual/expression-search#10]
```
Please add new expressions (in addition to is:mark) that will allow to search 
for starred (marked) messages:
is:star
is:starred

```

Original issue reported on code.google.com by `Andrzej....@gmail.com` on 16 Nov 2012 at 9:33

**Comment by jibe-b** [comment]
This expression is not referenced in the help page of the addon (at least the one accessed from the floating pop-up).

Thank you @GoogleCodeExporter for having implemented it, it is useful.
