### ISSUE TITLE
mail body filter problem with base64 encoded strings (URi data)

### ISSUE THREAD

**Issue by robstroess** [wangvisual/expression-search#102]
Hi. Neither "body contains" nor "body (regex) matches" filters work on mails containing URi data (base64 encoded strings) used more and more frequently by spammers to fend off simple regex filters for spammer ULRs found in a mail body.
Attached please find an example: body1enc.txt is the mail body, enc2ascii.txt is the decoded body (HTML source), filtercrit.txt is the string entered for a "body contains" or a "body (regex) matches" filter - neither work.

Please help - "expression-search" is so valuable to fight spam via filters that I even disabled Thunderbird updates (running 60.9.1/64 bit) just to be able to use "expression-search. Thunderbird's spam learning cannot cope with the function that "expression-search" allows. P.S. I already donated - and will do again if this problem could be solved.
Thanks in advance - Robert
[body1enc.txt](https://github.com/wangvisual/expression-search/files/5581076/body1enc.txt)
[enc2ascii.txt](https://github.com/wangvisual/expression-search/files/5581077/enc2ascii.txt)
[filtercrit.txt](https://github.com/wangvisual/expression-search/files/5581080/filtercrit.txt)

**Comment by xlovinglyx** [comment]
wang seems to be giving up, after months passing by, ignoring this. all that hard work for nothing.

**Comment by robstroess** [comment]
Thx for your response, xlovinglyx - how sad. Maybe I can attempt to create a fix though I am a bloody newbie regarding Thunderbird Extension programming and Thunderbird API ... first thing to do will probably be an update towards the newest Thunderbird release as I believe "expression search" does not work with 78.5.1.
Cheers - Robert

**Comment by robstroess** [comment]
Oops, after looking into the code I have to admit that this attempt would be way beyond my expertise. Instead, I'll be supporting RealRaven2000's FiltaQuilla to hopefully include a "Body (Regex) Match" soon. Btw.: I learned xlovinglyx already opted for such an improvement in https://github.com/RealRaven2000/FiltaQuilla/issues/75 .
