### ISSUE TITLE
Tooltip colors make the tips hard to read

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wangvisual/expression-search#27]
```
What steps will reproduce the problem?

1. View the tooltips (Ctrl-Shift-K)


What is the expected output? What do you see instead?

Expected: Clear, easy-to-read type.
Instead: Type that is exceedingly difficult to read.


What version of the product are you using? On what operating system?
Version 0.8.8. Ubuntu 14.04.

Please provide any additional information below.

Perhaps the easiest to read would be black type on a white background. Black on 
a very light grey can also work. White on black is another possible choice, but 
it works well only in somewhat larger type sizes.

There is no need for the tips to be in different colors.

A shorter line length would also be better. 

Thank you for the excellent plugin.







```

Original issue reported on code.google.com by `jasw...@gmail.com` on 30 Dec 2014 at 2:14

Attachments:
* [Expression search tooltips.png](https://storage.googleapis.com/google-code-attachments/expression-search/issue-27/comment-0/Expression search tooltips.png)
* [more_readable.png](https://storage.googleapis.com/google-code-attachments/expression-search/issue-27/comment-0/more_readable.png)

**Comment by shanness** [comment]
Hey there, thanks for such a great extension.  This problem still exists for me though :( 
![image](https://user-images.githubusercontent.com/631580/170873881-06d8ea1b-6f44-496e-83cc-a3191e2dd03a.png)
It's completely unreadable unfortunately  :(
