### ISSUE TITLE
Can't hide Quick Filter Bar

### ISSUE THREAD

**Issue by bvandergiessen** [wangvisual/expression-search#28]
As mentioned in a [review](https://addons.mozilla.org/en-US/thunderbird/addon/gmailui/reviews/693348/), if I put the Expression Search widget in the ToolBar, it is impossible to hide the Quick Filter Bar. Thunderbird simply doesn't allow it (in the menu: View... Toolbars... Quick Filter Bar). The empty bar keeps taking up space above the list of mails. (TB 31.5.0 and 31.6.0 on OS X 10.10.2)

I've put some screenshots below:
![visible quick search bar](https://cloud.githubusercontent.com/assets/11797190/6992851/e565b396-dae0-11e4-9766-02d2165307e6.png) Visible Quick Search Bar, taking up space between ToolBar and mail list

![menu](https://cloud.githubusercontent.com/assets/11797190/6992860/0479763c-dae1-11e4-820a-490d01c4ea5b.png) View menu, where the checkmark at "Quick Filter Bar" can't be deselected

![settings](https://cloud.githubusercontent.com/assets/11797190/6992866/21eb983a-dae1-11e4-8b19-8ed419bdb8b2.png) The settings for the extension.

**Comment by wangvisual** [comment]
Please try https://github.com/wangvisual/expression-search/blob/master/beta/gmailui-0.9-tb.xpi

**Comment by bvandergiessen** [comment]
Perfect, thanks!
