### ISSUE TITLE
Search not working properly - is there any way to re-index?

### ISSUE THREAD

**Issue by Gwalior-84** [wangvisual/expression-search#30]
Windows 8.1
TB 38.2.0

I type in search criteria but the add-on misses many messages that match that criteria.

Is this an indexing issue?  If so is there a way to re-index?

Any help, much appreciated.

Thanks, Mark.

**Comment by jpfleury** [comment]
See here to rebuild the global database: https://support.mozilla.org/en-US/kb/rebuilding-global-database

**Comment by Gwalior-84** [comment]
This appears to have fixed it, thanks.  I guess I should have known that it would take hours, and that I shouldn't try to do it when I'm trying to do some work... :-)
