### ISSUE TITLE
Search for attachment name not working

### ISSUE THREAD

**Issue by Yardarrat** [wangvisual/expression-search#31]
It seems like "filename/fi/fn/file" do not work at all. any instructions how to use it properly or a quick fix if it really is a bug would be awesome.

**Comment by wangvisual** [comment]
It requires mail synced/downloaded to local dsik.

**Comment by Olifair** [comment]
I have got the same problem, also on local folders : when searching "attachment:yes" I find only a few files, and most of the do actually not have an attachment. I'm using Thunderbird 60.5.1 and Expression Search 1.3
Actually size: and larger: do also not work on local folders.
