### ISSUE TITLE
0.9.1.-let-fixed cannot be installed

### ISSUE THREAD

**Issue by bege10** [wangvisual/expression-search#34]
Hi,
the lastet update cannot be installed, neither from Thunderbird add-on manager, nor by downloading from AMO. Both attempts end with error message.

**Comment by wangvisual** [comment]
Please try 1.0 release @ https://github.com/wangvisual/expression-search/blob/master/releases/gmailui-1.0-tb.xpi

**Comment by bege10** [comment]
Thank you, installation worked.
