### ISSUE TITLE
Thunderbird 45.0 - can not search

### ISSUE THREAD

**Issue by MarioKusek** [wangvisual/expression-search#40]
I have updated to Thunderbird 45.0 and now I can only search by words. If I put "from:mario" or any other keyword I get nothing.

**Comment by wangvisual** [comment]
Try https://addons.mozilla.org/en-US/thunderbird/addon/gmailui/versions/1.0

**Comment by derekriemer** [comment]
When I search for this add-on in thunderbird, the 1.0 version isn't the latest. It says 0.9 for some reason. are you aware of this? Also thanks for this add-on. The default thunderbird search does not work at all with screen readers, but this add-on saves me a lot of time.

**Comment by MarioKusek** [comment]
I have install it and it works fine on TB45 on Mac.
Thanks

**Comment by wangvisual** [comment]
I just upload the 1.0 version to mozilla thunderbird, it's still under review process, that's why 0.9 is show as the latest version.
