### ISSUE TITLE
Inverted search?

### ISSUE THREAD

**Issue by embeh** [wangvisual/expression-search#47]
Maybe I am missing something but it seems that we currently cannot exclude something from search?
E.g. find all messages that are *not* from bob@host.com?

I tried 'not', '~', '!', '-' as operators but none seemed to work.

Thanks!

**Comment by wangvisual** [comment]
from:-bob@host.com

**Comment by embeh** [comment]
Thanks! Slightly unexpected notation but seems to work. 
Might be worth to include that example in the help window?
