### ISSUE TITLE
Invalid results included

### ISSUE THREAD

**Issue by patricktokeeffe** [wangvisual/expression-search#50]
Using the 2017-04-05 version with TB 45.8.0, the search term "`rma`" returns 938 of the 1650 messages in my inbox. Many of the so-called results do not contain that term at all and nearly all of the rest only contain that term *within* other words (for example: info`rma`tion). This seems incredibly wrong.

![2017_04_21_14_30_00_inbox_exchange_mozilla_thunderbird](https://cloud.githubusercontent.com/assets/1348834/25297132/d0f0be20-26a0-11e7-9256-5fa4ad797946.png)

![2017_04_21_14_29_15_inbox_exchange_mozilla_thunderbird](https://cloud.githubusercontent.com/assets/1348834/25297131/cc5ea80e-26a0-11e7-902d-0fd0bf207ee4.png)

**Comment by patricktokeeffe** [comment]
I think the wrong content is being searched... 

Here, I've searched for "asset tag" and received 1 result that contains no instances of "asset" or "tag" anywhere in the message body:

![2017_04_26_15_29_05_sent_items_exchange_mozilla_thunderbird](https://cloud.githubusercontent.com/assets/1348834/25460040/48b43b5a-2a96-11e7-9c4c-d0652bdd3f59.png)

But the message source itself *does* contain (words that contain) the search terms: 

![2017_04_26_15_39_14_source_of_imap_pokeeffe_connect wsu edu_993_fetch_3euid_3e_sent_20items_3e220](https://cloud.githubusercontent.com/assets/1348834/25460490/92b26ca2-2a98-11e7-92d3-26371f6952b9.png)

I see two things wrong here:

* terms matched within words (possibly by design? not addressed in options)
* underlying HTML source is indexed as if it were message body

**Comment by wangvisual** [comment]
This is the TB builtin search box, possibly expression search inherit the same issue, but I would like to suggest create bug report against TB itself.

**Comment by patricktokeeffe** [comment]
I agree it's probably TB. Thanks for closing
