### ISSUE TITLE
Search is VERY slow and makes UI unusable

### ISSUE THREAD

**Issue by qrzychu** [wangvisual/expression-search#51]
When I type anything in the search box, TB UI almost freezes for a rather long period of time. Few results come up almost immediately, but I have to wait for the rest.

Windows Task Manager shows that Thunderbird uses 27% of processor, which means it uses one core to its full power. I cannot do anything until the search is over.

Maybe you should make it multithreaded? Or at least move search out of a UI thread - it is really bad. And even a little progress bar would be great, something like "Searching through 1234/10000".

**Comment by LatinSuD** [comment]
What search string are you using?

Do you use normal search AND you have "Body" button enabled? That is a TB bug by itself

**Comment by qrzychu** [comment]
yeah, disabling "Body" makes it faster, but still it freezes the UI. 

Still, this is not really a workaround, because I want to search in body too. I have 2 email accounts defined, one has only 2500 emails - it still can get a little laggy. 

My machine has i5 processor, 16gb RAM and SSD drive - it's pretty fast. 
Maybe there is a way to limit overhead while searching (for example use only 2 cores) to keep UI responsive?

**Comment by LatinSuD** [comment]
That would be nice.

Keep in mind that Thunderbird has already 2 types of builtin search: Quick filter and Global search.
Global search can do fast body search, but I think this extension currently works by extending Quick Filter. So i'm not sure if it would be easy to do the job you request.

**Comment by qrzychu** [comment]
I use your extension, because built in ones suck so much that it is not even funny :D it looks more like random emails then search results.
 I guess that there is somewhere a foreach loop on all emails, which goes concurently. I don't know JS, but there should be a way to limit number of threads. This could be option, to let other people who do not suffer UI lag.

Thanks for all responses :)

**Comment by wangvisual** [comment]
Can't reproduce, I have more than 10000 mails in one folder and the search speed is still acceptable, as long as you have other filters that not depend on email body.
