### ISSUE TITLE
Searching Headers does not work

### ISSUE THREAD

**Issue by eqjjh** [wangvisual/expression-search#52]
In the "Preferences" I added "Delivered-To" under the section "Search more headers" but the expression search does not work on this field. 

Eg, I searched on an e-mail address, and I am missing a lot of results. 

I tried restarting thunderbird after making this change. I am using version 45.8.0.

**Comment by wangvisual** [comment]
The additional headers information is only updated for newer emails, you might need to repair the mail folder to make it work for old emails.

Right click mail folder, click properties, then click repair folder.
