### ISSUE TITLE
Broken since thunderbird upgrade to 56.0b1 version

### ISSUE THREAD

**Issue by jreybert** [wangvisual/expression-search#53]
I get this error at startup.

```
Caught Exception NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIXPCComponents_Utils.import]
@resource://expressionsearch/ExpressionSearchFilter.js:12:1
importModules@chrome://expressionsearch/content/es.js:59:5
init@chrome://expressionsearch/content/es.js:27:9
@chrome://expressionsearch/content/es.js:753:1
JS frame :: resource://expressionsearch/ExpressionSearchFilter.js :: <TOP_LEVEL> :: line 12
```

Don't know if it is related, but a new search text box appeared on the interface. I still have `Ctrl+K` and `Ctrl+Shift+K` text boxes, and a new one. This new text box does nothing.

**Comment by wangvisual** [comment]
Please try the version 1.1 beta @ https://github.com/wangvisual/expression-search/blob/master/beta/
Thanks.

**Comment by jreybert** [comment]
It works like a charm, thanks.

What is this new dropmenu for? It shows option1 option2 option3 option4 for the moment.

**Comment by wangvisual** [comment]
Please ignore it, I forgot to remove it when create the beta version :-(

**Comment by jreybert** [comment]
If you mind to create a new beta .xpi file without this dropmenu, let me know :)

**Comment by wangvisual** [comment]
Try this:
https://github.com/wangvisual/expression-search/blob/master/releases/gmailui-1.1-tb.xpi
Thanks.

**Comment by jreybert** [comment]
Excellent! 👍
