### ISSUE TITLE
Add a fromto operator

### ISSUE THREAD

**Issue by jreybert** [wangvisual/expression-search#54]
In thunderbird, I already have a view with sent and received mails.

When searching for a conversation, it helps to have both sent and received mails to a contact.

**Comment by wangvisual** [comment]
Did you mean that if user input:fromto xyz
Then if xyz in from OR xyz in to/cc, the mail will be matched?

**Comment by jreybert** [comment]
Exactly

**Comment by wangvisual** [comment]
You can try 1.2beta now.
https://github.com/wangvisual/expression-search/blob/master/beta/gmailui-1.2-tb.xpi

**Comment by jreybert** [comment]
Excellent, gmailui moves from must have to vital addon!

It works as expected, you can close the issue.
