### ISSUE TITLE
Functionality no longer works with TB 52.2.1

### ISSUE THREAD

**Issue by infogrind** [wangvisual/expression-search#55]
Hi,

I'm running TB 52.2.1 (64-bit) on OS X 10.12.6. Until recently, the Expression Search add-on has been working flawlessly hand has been a major productivity improvement for me - thanks!

Today I've noticed that the search field no longer works. I have disabled all other add-ons and I have also removed and reinstalled the Expression Search add-on, without success.

**ACTUAL situation:**

- There are two search fields in the quick search bar, the usual one and a second one to the right (presumably this is the one generated by the add-on)
- The usual (built-in) search field works as expected.
- Nothing happens when I type in the other field. (Not even the tool tip is shown.

In the log (Tools/Developer Tools/Error Console) I see the following:

    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getIntPref]  log.js:19
    	<anonymous>                                   resource://expressionsearch/log.js:19:15
	    ExpressionSearchChrome.init               chrome://expressionsearch/content/es.js:23:5
    	<anonymous>                              chrome://expressionsearch/content/es.js:767:1

See screenshot: http://imgur.com/a/AyyGv for what it looks like in TB.

**EXPECTED situation:**

- Only one search field is shown (in the preferences, "Hide normal filter" is checked).
- Search works as expected.

Thanks in advance for looking into this!

**Comment by infogrind** [comment]
How I have been able to fix it: use the config editor (Preferences/Advanced) to manually add an integer preference called `alerts.totalOpenTime` and setting it to 4000 [ms].

Perhaps the new version of Thunderbird doesn't have this config value anymore built in.

**Comment by ldexterldesign** [comment]
+1

**Comment by wangvisual** [comment]
Confirmed, the default setting was removed on OS X.
https://bugzilla.mozilla.org/show_bug.cgi?id=1290324

**Comment by zozimus1** [comment]
Bingo - thanks!!

**Comment by wangvisual** [comment]
fixed by https://github.com/wangvisual/expression-search/commit/e1a6b2b60651baeedd682cc36fb4c3ccc9a03ad2
