### ISSUE TITLE
Seems to Have Stopped Working in Thunderbird 52.2.1 on OSX

### ISSUE THREAD

**Issue by jeetsukumaran** [wangvisual/expression-search#57]
The text box appears in its usual place in the quick filter bar. But there is no effect: i.e., typing into the box, hitting return, etc. does not produce any results or filtering.

**Comment by jph108** [comment]
Me too. There seem to now be two search boxes. The one on the left works.
![thunderbird search](https://user-images.githubusercontent.com/1222784/29281558-7cc01254-80ed-11e7-9642-adb3702f5d20.png)

**Comment by jeetsukumaran** [comment]
The one on the left is the default/stock Quick Filter box.

**Comment by jph108** [comment]
No, I think that's the one on the top.

**Comment by jeetsukumaran** [comment]
Nope, the one on top is the full search box (it opens a new window with search results), not the default/stock quick filter (which filters in place). If you disable all your extensions/add-ons, the one on the left remains (as does the one on top).

**Comment by JoshLitt** [comment]
I have the same issue, on same TBird version, also MacOS. Same "dead" expression filter box to the right of the normal Quick Filter box.

**Comment by mr-mmmmore** [comment]
Same here: same version of TB on Mac OS, both input appear like in the screenshot, no feature of the plugin work (search, quick filter with Ctrl+Right click...)

**Comment by wangvisual** [comment]
duplicate with #55 
1.2 was submitted to AMO for review, before reviewed, you can try this one:
https://github.com/wangvisual/expression-search/blob/master/releases/gmailui-1.2-tb.xpi

**Comment by scfcode** [comment]
With the build above, on TB 52.2.1 and macOS 10.12.6 it appears to be back working again.

Only one search field (aside from the command K one) and that now works with queries again.

A big thank you to the author!! Much appreciated.

**Comment by mr-mmmmore** [comment]
Fixed here too! Thanks!
👍

**Comment by jeetsukumaran** [comment]
Fixed for me as well. Thanks!
