### ISSUE TITLE
Mac OS - version 1.2 - the search window appears ABOVE the tabs

### ISSUE THREAD

**Issue by jph108** [wangvisual/expression-search#58]
Hello,
I just installed the latest version (https://github.com/wangvisual/expression-search/blob/master/releases/gmailui-1.2-tb.xpi). I'm getting something funny, because the search box now appears above the Thunderbird tabs. Please see first screenshot Also, when I try to remove the extension and re-install, the extension still functions after being removed (the Quick Filter box is still there). 

![image](https://user-images.githubusercontent.com/1222784/29423252-0693e2a0-8349-11e7-88ee-f354ce63bd0e.png)

This is with all extensions disabled, and Expression-Search removed. 
![image](https://user-images.githubusercontent.com/1222784/29423411-a4a0e9c0-8349-11e7-9697-3a5769abec94.png)

Thanks and Best Regards,
Josh

**Comment by wangvisual** [comment]
Please try to change the option
![capture-1](https://user-images.githubusercontent.com/1171579/29460686-6d9fe508-845b-11e7-8071-0241b88cf4cf.jpg)
