### ISSUE TITLE
Ctrl/Shift+Right Click to search the clicked subject/From/Recipient -- NOT WORKING

### ISSUE THREAD

**Issue by IeUDE** [wangvisual/expression-search#67]
> Use Ctrl/Shift+Right Click to search the clicked subject/From/Recipient.

This feature is not working for me

when I either ctrl + right mouse click (or shift + right mouse click) a subject's message (or recipient's, etc.), nothing happens from the side of expression search extension.

Just a drop down menu appear, what am I missing?

Using TB 60.0b10 (32-bit).

![thunderbird_2018-07-25_13-44-17](https://user-images.githubusercontent.com/1016790/43199089-1a4b4c40-9011-11e8-9c20-0203775f6c42.jpg)

**Comment by wangvisual** [comment]
You need to Ctrl+click on the mail list pane, not the mail header pane.
