### ISSUE TITLE
Not compatible with 60.2.1

### ISSUE THREAD

**Issue by biva** [wangvisual/expression-search#71]
Hello,
Thank you for your fantastic add-on: I use it every day :)
I just wanted to let you know that it appears as not compatible with the last version of TB: 60.2.1
Thank you again

**Comment by wangvisual** [comment]
Did you mean it works with 60 but not 60.2.1?

You can try this one:
https://github.com/wangvisual/expression-search/blob/master/beta/gmailui-1.4-tb.xpi

This is mainly for TB61+, so has a lot of changes.

**Comment by biva** [comment]
> Did you mean it works with 60 but not 60.2.1?
Yes

I'll have a look at your beta version: can I use it safely? It will not break Thunderbird?

**Comment by wangvisual** [comment]
No, it won't break, if it does not work, you can uninstall it and install the 1.3 version.

Myself using 1.4 beta with TB nightly :-)

**Comment by biva** [comment]
OK, I installed it, but same result: it doesn't work. I can't even see the toolbar :(

**Comment by biva** [comment]
Hello @wangvisual , were you able to make progress with the last version of TB? I miss your addon :(
Thank you, and available for testing!

**Comment by biva** [comment]
Hello @wangvisual : any update on this issue? It still doesn't work on 60.3.1 :(

**Comment by pfolk** [comment]
This stopped working for me recently as well. Thunderbird refuses to install 1.4beta because it isn't compatible.  Per the 64.0beta release notes https://www.thunderbird.net/en-US/thunderbird/64.0beta/releasenotes/: (in bold at the top of the list =): **ADD-ON SUPPORT: Restartless add-ons continue to work if their authors have made the necessary minor adjustments. Non-restartless legacy add-ons using XUL overlays are only supported if add-on authors have adapted them, and Lightning/Calendar is the only one we know that has been adapted.**

...seems related.

**Comment by biva** [comment]
Hello @wangvisual I just updated TB to 60.4 and your addon still doesn't work. I can open the "Options" windows but I can't see the Expression search bar :( Any idea?
Thank you!

**Comment by biva** [comment]
Hello @wangvisual I just updated TB to 60.5 and still the same issue :( Your addon still doesn't work. I can open the "Options" windows but I can't see the Expression search bar :( Any idea?
I can test anything if you want.
Thank you!

**Comment by wangvisual** [comment]
I don't know why but 1.4 beta works for me for both TB 60.4, 60.5 and TB 66 nightly.

You can try the 1.4 beta at https://github.com/wangvisual/expression-search/blob/master/beta/gmailui-1.4-tb.xpi

And if doesn't work you can check the error log in Error Console (Ctrl+Shift+J)

**Comment by biva** [comment]
Hi @wangvisual Thanks for your message. I installed the beta: no change, it doesn't work
I deactivated all other addons: no change.
The Error Console says:
`1548952630183	addons.xpi	WARN	Error loading bootstrap.js for {03EF8A6E-C972-488f-92FA-98ABC2C9F8B9}: Error opening input stream (invalid filename?): jar:file:///C:/Users/Etienne/AppData/Roaming/Thunderbird/Profiles/3wq7xz3a.TB64bits/extensions/%7B03EF8A6E-C972-488f-92FA-98ABC2C9F8B9%7D.xpi!/bootstrap.js`

`1548952630184	addons.xpi	WARN	Add-on {03EF8A6E-C972-488f-92FA-98ABC2C9F8B9} is missing bootstrap method startup`

**Comment by biva** [comment]
(03EF8A6E-C972-488f-92FA-98ABC2C9F8B9 This addon is Expression Search)

**Comment by wangvisual** [comment]
I see, the file was missing when doing release, please try again, same location.

**Comment by biva** [comment]
Yes! It works now. To be clear, when I installed it did not work. In order to make it work, I deactivated all other addons, then Expression Search worked, then I activated the other addons, and Expression Search is still working.

Thanks!
