### ISSUE TITLE
Not compatible with thunderbird 63.0b1(or even with 64.0a1)

### ISSUE THREAD

**Issue by jreybert** [wangvisual/expression-search#73]
Since a recent thunderbird update (can't remember exactly, around mid October 2018), gmailui does not work anymore.

I tried the 1.4 beta, it does not work better.

Symptom: when I type from:username in the filter textbox, mails are not filtered anymore.

**Comment by biva** [comment]
Related to https://github.com/wangvisual/expression-search/issues/71 ?

**Comment by karlbu** [comment]
Thank you for the new beta 1.4 on 1/31!  Working now with 60.5.

**Comment by jreybert** [comment]
I confirm the last beta 1.4 works with 60.5, and also works with last thunderbird beta 65.0b4.
I believe you can close this issue now.

**Comment by jreybert** [comment]
I see I missed the occasion for thanking you for this plugin!

This is the most useful addon I ever used with thunderbird, thanks a lot for this!

**Comment by wangvisual** [comment]
jreybert, You're welcome. I know it's later for updating but I'm too busy with my job.

**Comment by tonycpsu** [comment]
Am I missing something about how the operation of the plugin has changed with newer Thunderbird releases?  I'm on 60.5.0 and I have the 1.4 beta installed.  When I type from:(name) or to:(name), the messages in the inbox are not filtered like they would normally be.  If I hit enter, the awful Thunderbird built-in search comes up with its usual bad results.

**Comment by jreybert** [comment]
@tonycpsu I think that @wangvisual did not release the last beta in thunderbird repository. You need to fetch it manually et install from file:
https://github.com/wangvisual/expression-search/raw/master/beta/gmailui-1.4-tb.xpi

**Comment by tonycpsu** [comment]
Yeah, I did in fact download the beta from that link.

**Comment by tonycpsu** [comment]
@wangvisual: that fixed it.  Thank you!
