### ISSUE TITLE
Not compatible with current (2019-09-13) trunk

### ISSUE THREAD

**Issue by jikamens** [wangvisual/expression-search#81]
Code is incompatible with TB trunk as of 2019-09-13.

I was able to get the exceptions to go away on startup with the attached patch. Now it logs a startup message and nothing else, but the quick filter box still doesn't except Google syntax.

[diff.txt](https://github.com/wangvisual/expression-search/files/3609554/diff.txt)

**Comment by wangvisual** [comment]
Only can focus on TB68 now, trunk is removing everything that addon needed...
