### ISSUE TITLE
Filter not working only search?

### ISSUE THREAD

**Issue by RalfRoemling** [wangvisual/expression-search#91]
I'm new to this addon and therefore don't know how it's designed to work, so sorry if I'm asking a dumb question :-)

On the Mozilla addons page it seems it's been used as a filter similar to the QuickFilter function. When I install it it's only working as Search and displaying the results in the normal search results page.

Can I get it to work as a filter somehow?

**Comment by riedel** [comment]
Stupid question: since you are new, do you have a TB version >=68? So might it be related to #80?

on TB 60.x it work by typing anything like in https://cdn.rawgit.com/wangvisual/expression-search/master/content/help.html and it should restrict the messages you see like the normal quick search

**Comment by RalfRoemling** [comment]
Hi Till, yeah quite right, I'm on TB 68.6 and yes, if is supposed to work as you describe it, it's the same as #80 . Ticket#s closed.
